ServerRunTests: 

```
----------------------- Проверка flake8 пройдена -----------------------

============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-5.3.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
rootdir: /app, inifile: pytest.ini, testpaths: tests/
plugins: django-3.8.0
collecting ... collected 20 items

tests/test_homework.py::TestRecord::test_init[kwargs0] FAILED            [  5%]
tests/test_homework.py::TestRecord::test_init[kwargs1] FAILED            [ 10%]
tests/test_homework.py::TestCalculator::test_init PASSED                 [ 15%]
tests/test_homework.py::TestCalculator::test_add_record PASSED           [ 20%]
tests/test_homework.py::TestCalculator::test_get_today_stats PASSED      [ 25%]
tests/test_homework.py::TestCalculator::test_get_week_stats FAILED       [ 30%]
tests/test_homework.py::TestCalculator::test_get_calories_remained PASSED [ 35%]
tests/test_homework.py::TestCalculator::test_get_today_cash_remained PASSED [ 40%]
tests/test_homework.py::TestCaloriesCalculator::test_init PASSED         [ 45%]
tests/test_homework.py::TestCaloriesCalculator::test_get_calories_remained FAILED [ 50%]
tests/test_homework.py::TestCashCalculator::test_init FAILED             [ 55%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[0-usd] FAILED [ 60%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[0-eur] FAILED [ 65%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[0-rub] FAILED [ 70%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[1-usd] FAILED [ 75%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[1-eur] FAILED [ 80%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[1-rub] FAILED [ 85%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[-1-usd] FAILED [ 90%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[-1-eur] FAILED [ 95%]
tests/test_homework.py::TestCashCalculator::test_get_today_cash_remained[-1-rub] FAILED [100%]

=================================== FAILURES ===================================
/app/tests/test_homework.py:54: AssertionError: Неверное значение свойства `date` у класса `Record`, свойство должно быть датой
/app/tests/test_homework.py:40: AssertionError: В качестве дефолтного аргумента для даты не должно быть посчитанное значение или пустая строка
/app/tests/test_homework.py:97: AssertionError: Проверьте правильность работы метода `get_week_stats()` у класса `Calculator`
/app/tests/test_homework.py:142: AssertionError: Проверьте правильность работы метода `get_calories_remained()` у класса `CaloriesCalculator`
/app/tests/test_homework.py:170: AssertionError: Неверное значение свойства `EURO_RATE` у класса `CashCalculator`
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
/usr/local/lib/python3.7/re.py:178: TypeError: expected string or bytes-like object
========================= 14 failed, 6 passed in 0.29s =========================
```
ы